schema_version = "1.0.0"
id = "blender_colormaps"
version = "1.3.0"
name = "Blender Colormaps"
tagline = "Import curated or custom colormaps into Blender"
maintainer = "Jeran Poehls"
type = "add-on"
website = "https://github.com/TheJeran/Blender-Colormaps"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]